DATASET:
    train_list: []    
    # PW3D  
    test_list: ['PW3D']               
    workers: 16

MODEL:
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    weight_path: 'experiment/exp_02-11_15:15/checkpoints/best.pth.tar'
    input_img_shape: [256, 192]
    predictor_hidden_dim: 256
    
TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 10