DATASET:
    train_list: []    
    # PW3D  
    test_list: ['MuPoTS']               
    workers: 4

MODEL:
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    normalize_imagenet: True
    weight_path: 'experiment/final/exp_02-27_02_26/checkpoints/best.pth.tar'
    input_img_shape: [256, 192]

TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 100