DATASET:
    train_list: [] 
    test_list: ['MSCOCO']               
    workers: 16

MODEL:
    type: '2d_joint'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'    
    weight_path: '/home/namhj/PoseContrast/experiment/exp_10-12_15:48:35/checkpoints/final.pth.tar'
    use_upsampling_layer: True
    input_img_shape: [256, 192]
    
TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 10