DATASET:
    train_list: []    
    # MSCOCO
    test_list: ['MSCOCO']               
    workers: 16

MODEL:
    type: '2d_joint'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: True
    weight_path: 'experiment/pretrained_2d_joint_upresnet_mscoco/checkpoints/final.pth.tar'
    input_img_shape: [256, 192]
    
TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 10