DATASET:
    train_list: []    
    # PW3D  
    test_list: ['MSCOCO']               
    workers: 4

MODEL:
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    weight_path: 'experiment/exp_03-03_14_32/checkpoints/best.pth.tar'
    input_img_shape: [256, 192]

TEST:
    batch_size: 4
    shuffle: False
    vis: True
    vis_freq: 10