DATASET:
    train_list: []    
    # PW3D  
    test_list: ['PW3D']               
    workers: 16

MODEL:
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    weight_path: '/home/namhj/PoseContrast/experiment/exp_10-10_15:15:25/checkpoints/epoch_60.pth.tar'
    input_img_shape: [256, 192]

TEST:
    batch_size: 128
    shuffle: False
    vis: True
    vis_freq: 10