DATASET:
    train_list: []   
    test_list: ['AGORA']               
    workers: 4

MODEL:
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    normalize_imagenet: False
    weight_path: 'experiment/exp_07-21_15:15:22/checkpoints/best.pth.tar'
    input_img_shape: [256, 192]

TEST:
    batch_size: 1
    shuffle: False
    vis: True
    vis_freq: 100