DATASET:
    # 'MSCOCO'
    train_list: ['MSCOCO']    
    # PW3D  
    test_list: []
    train_partition: [1.0]
    make_same_len: True
    workers: 16

MODEL:
    type: 'contrastive'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    input_img_shape: [256, 192]
    projector_hidden_dim: 512
    projector_out_dim: 512

TRAIN:      
    # 'pose', 'cls'
    pretrained_model_type: 'pose'
    transfer_backbone: True
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 50
    optimizer: 'adam'
    scheduler: 'step'
    lr: 0.001
    lr_step: [30, 40]
    lr_factor: 0.1
    print_freq: 10
    non_joints_num: 24
    heatmap_sigma: 10
    vis: True

AUG:
    scale_factor: 0.25
    rot_factor: 30
    color_factor: 0.2
    flip: True
