DATASET:
    # 'Human36M', 'MSCOCO', 'MPII', 'MPI_INF_3DHP', 'PW3D'
    train_list: ['Human36M', 'MSCOCO']
    train_partition: [0.5, 0.5] 
    # PW3D  
    test_list: ['PW3D']   
    make_same_len: True    
    workers: 16

MODEL:
    # 'contrastive', 'body', 'hand', '2d_joint'
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    weight_path: 'experiment/exp_01-20_20:01/checkpoints/epoch_120.pth.tar'
    input_img_shape: [256, 192]
    predictor_hidden_dim: 256

TRAIN:
    # 'posecontrast', 'pose', 'cls'
    pretrained_model_type: 'posecontrast'
    transfer_backbone: True
    freeze_backbone: False
    batch_size: 196
    shuffle: True 
    begin_epoch: 1
    end_epoch: 10
    optimizer: 'adam'
    scheduler: 'step'
    lr: 1.0e-4
    lr_step: []
    lr_factor: 0.1
    print_freq: 10
    use_pseudo_GT: True
    vis: False

    joint_loss_weight: 1.0
    proj_loss_weight: 0.1
    pose_loss_weight: 1.0
    shape_loss_weight: 1.0
    prior_loss_weight: 0.0
    
AUG:
    scale_factor: 0.25
    rot_factor: 30
    color_factor: 0.2
    flip: True

TEST:
    batch_size: 32
    shuffle: False
    vis: False
    vis_freq: 100