DATASET:
    # 'Human36M', 'MSCOCO', 'MPII', 'MPI_INF_3DHP', 'PW3D'
    train_list: ['MSCOCO']   
    #train_partition: [1.0]
    # PW3D  
    test_list: []   
    make_same_len: True    
    workers: 16

MODEL:
    # 'contrastive', 'body', 'hand', '2d_joint'
    type: '2d_joint'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: True
    input_img_shape: [256, 192]

TRAIN:
    transfer_backbone: False
    freeze_backbone: False
    batch_size: 128
    shuffle: True 
    begin_epoch: 1
    end_epoch: 140
    optimizer: 'adam'
    scheduler: 'step'
    lr: 1.0e-3
    lr_step: [90, 120]
    lr_factor: 0.1
    print_freq: 10
    vis: True

    heatmap_sigma: 2.0
    hm_loss_weight: 1.0
    
AUG:
    scale_factor: 0.3
    rot_factor: 40
    color_factor: 0.2
    blur_factor: 0.0
    shift_factor: 0.0
    flip: True

TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 20