DATASET:
    # 'MSCOCO'
    train_list: ['MSCOCO']    
    # PW3D  
    test_list: []
    train_partition: [1.0]
    make_same_len: True
    workers: 16

MODEL:
    type: 'contrastive'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    input_img_shape: [256, 192]
    projector_hidden_dim: 1024
    projector_out_dim: 1024
    weight_path: 'experiment/exp_01-27_14:22/checkpoints/epoch_24.pth.tar'

TRAIN:      
#    from_scratch: True
    pretrained_model_type: 'pose'
    batch_size: 64  #128 #
    shuffle: True
    begin_epoch: 1
    end_epoch: 140  #30
    optimizer: 'adam'
    scheduler: 'step'
    lr: 0.01
    lr_step: [80, 120]
    lr_factor: 0.1
    print_freq: 10
    non_joints_num: 24
    heatmap_sigma: 10
    vis: False
    num_view: 4  #2  #

AUG:
    scale_factor: 0.25
    rot_factor: 30
    color_factor: 0.2
    flip: True
