DATASET:
    # 'MSCOCO'
    train_list: ['MSCOCO']    
    # PW3D  
    test_list: []
    train_partition: [1.0]
    make_same_len: True
    workers: 16

MODEL:
    type: 'contrastive'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: True
    input_img_shape: [256, 192]
    projector_hidden_dim: 256
    projector_out_dim: 256

TRAIN:      
    transfer_backbone: False
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 80
    warmup_epoch: 3
    optimizer: 'adam'
    scheduler: 'step'  #'step', 'cosine'
    lr: 0.001
    min_lr: 1.0e-6
    lr_step: [50, 70]
    lr_factor: 0.1
    print_freq: 10
    heatmap_sigma: 2.0
    vis: False

    contrast_loss_weight: 1.0
    temperature: 0.1

AUG:
    scale_factor: 0.3
    rot_factor: 40
    color_factor: 0.2
    blur_factor: 0.0
    shift_factor: 0.0
    flip: True
