DATASET:
    train_list: ['MSCOCO']    
    test_list: ['MSCOCO']               
    workers: 16

MODEL:
    type: '2d_joint'
    # 'resnet50', 'resnet50-fpn', 'hrnet'
    backbone: 'resnet50'    
    input_img_shape: [256, 192]
    backbone_out_dim: 256
    projector_hidden_dim: 1024
    projector_out_dim: 24

TRAIN:      
    finetuning: False
    batch_size: 256
    shuffle: True
    begin_epoch: 1
    end_epoch: 50
    optimizer: 'adam'
    scheduler: 'step'
    lr: 0.001
    lr_step: [40, 45]
    lr_factor: 0.1
    print_freq: 10

    inter_joint_loss_weight: 1.0
    intra_joint_loss_weight: 1.0

AUG:
    scale_factor: 0.25
    rot_factor: 30
    color_factor: 0.2
    flip: True

TEST:
    batch_size: 64
    shuffle: False
    vis: True