DATASET:
    # train_list: ['MSCOCO']    
    # test_list: ['MSCOCO']   
    train_list: ['YT3D']    
    test_list: []
    workers: 16

MODEL:
    type: '2d_hand'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'    
    use_upsampling_layer: True
    input_img_shape: [256, 192]

TRAIN:  
    transfer_backbone: False
    freeze_backbone: False
    batch_size: 128
    shuffle: True 
    begin_epoch: 1
    end_epoch: 80
    optimizer: 'adam'
    scheduler: 'step'
    lr: 0.001
    min_lr: 1.0e-6
    lr_step: [50, 70]
    lr_factor: 0.1
    print_freq: 10
    heatmap_sigma: 2.0
    vis: True

    hm_loss_weight: 1.0

AUG:
    scale_factor: 0.3
    rot_factor: 40
    color_factor: 0.2
    blur_factor: 0.0
    shift_factor: 0.0
    flip: True

TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 10