DATASET:
    # 'Human36M', 'MSCOCO', 'MPII', 'MPI_INF_3DHP', 'PW3D'
    train_list: ['MPII']   
    #train_partition: [1.0]
    # PW3D  
    test_list: []   
    make_same_len: True    
    workers: 16

MODEL:
    # 'contrastive', 'body', 'hand', '2d_joint'
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    weight_path: 'experiment/pose_pretrained_download/checkpoints/pose_resnet_50_256x192.pth'
    input_img_shape: [256, 192]

TRAIN:
    transfer_backbone: False
    freeze_backbone: False
    batch_size: 128
    shuffle: True 
    begin_epoch: 1
    end_epoch: 30
    optimizer: 'adam'
    scheduler: 'step'
    lr: 1.0e-4
    lr_step: [20]
    lr_factor: 0.1
    print_freq: 10
    use_pseudo_GT: True
    vis: False

    joint_loss_weight: 1.0
    proj_loss_weight: 0.1
    pose_loss_weight: 1.0
    shape_loss_weight: 1.0
    prior_loss_weight: 0.0
    
AUG:
    scale_factor: 0
    rot_factor: 0
    color_factor: 0.0
    flip: False

TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 200