DATASET:
    # 'MSCOCO'
    train_list: ['MSCOCO']    
    # PW3D  
    test_list: []
    train_partition: [1.0]
    make_same_len: True
    workers: 16

MODEL:
    type: 'contrastive'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    input_img_shape: [256, 192]
    projector_hidden_dim: 512
    projector_out_dim: 512

TRAIN:      
    # 'pose', 'cls'
    pretrained_model_type: 'cls'
    transfer_backbone: True
    batch_size: 128
    shuffle: True
    begin_epoch: 1
    end_epoch: 80
    warmup_epoch: 3
    optimizer: 'adam'
    scheduler: 'cosine'
    lr: 0.001
    min_lr: 1.0e-6
    lr_step: [40, 60]
    lr_factor: 0.1
    print_freq: 10
    non_joints_num: 12
    heatmap_sigma: 1.0
    vis: False

    inter_joint_loss_weight: 1.0
    intra_joint_loss_weight: 0.1
    temperature: 1.0

AUG:
    scale_factor: 0.25
    rot_factor: 30
    color_factor: 0.2
    blur_factor: 1.0
    shift_factor: 0.0
    flip: True
