DATASET:
    # 'Human36M', 'MSCOCO', 'MPII', 'MPI_INF_3DHP', 'PW3D'
    train_list: ['MSCOCO', 'Human36M']
    #train_partition: [1.0]
    # PW3D  
    test_list: ['PW3D']   
    make_same_len: True    
    workers: 4
    do_subsampling: True
    subsampling_ratio: 0.6


MODEL:
    # 'contrastive', 'body', 'hand', '2d_joint'
    type: 'body'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    normalize_imagenet: True
    weight_path: 'experiment/pretrained_2d_ms_from_scratch/checkpoints/final.pth.tar'
    input_img_shape: [256, 192]

TRAIN:
    transfer_backbone: False
    freeze_backbone: False
    batch_size: 128
    shuffle: True 
    begin_epoch: 1
    end_epoch: 120
    optimizer: 'adam'
    scheduler: 'step'
    lr: 1.0e-4
    lr_step: [90]
    lr_factor: 0.1
    print_freq: 10
    use_pseudo_GT: True
    vis: True

    joint_loss_weight: 1.0
    proj_loss_weight: 0.1
    pose_loss_weight: 1.0
    shape_loss_weight: 1.0
    prior_loss_weight: 0.0
    
AUG:
    scale_factor: 0.25
    rot_factor: 30
    color_factor: 0.2
    flip: True

TEST:
    batch_size: 32
    shuffle: False
    vis: True
    vis_freq: 200