DATASET:
    # 'MSCOCO'
    train_list: ['MSCOCO']    
    # PW3D  
    test_list: []
    train_partition: [1.0]
    make_same_len: True
    workers: 16

MODEL:
    type: 'contrastive'
    # 'resnet50', 'hrnetw32'
    backbone: 'resnet50'
    use_upsampling_layer: False
    input_img_shape: [256, 192]
    projector_hidden_dim: 2048
    projector_out_dim: 128

TRAIN:      
    transfer_backbone: False
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 140
    optimizer: 'adam'
    scheduler: 'step' 
    lr: 1.0e-3
    lr_step: [90, 120]
    lr_factor: 0.1
    print_freq: 10
    heatmap_sigma: 2.0
    vis: True

    contrast_loss_weight: 1.0
    temperature: 0.07

AUG:
    scale_factor: 0.3
    rot_factor: 40
    color_factor: 0.2
    blur_factor: 0.0
    shift_factor: 0.0
    flip: True
